### PR TITLE
Add hidden option for preferring windows over tabs

### PR DESCRIPTION
**Pull request by lydell**
Addresses #54.

In short:

- `Alt+K` and `Alt+Shift+K` opens links in new background _windows_ instead of tabs. Note: Firefox seems to _always_ focus new windows currently, while Chrome is able to open windows in the background. So on Firefox, Alt+K and Alt+L are effectively the same, and Alt+Shift+K just feels broken when you use it.
- `Alt+L` opens links in new foreground _windows_ instead of tabs.
- Holding `Alt` while activating a hint opens the link in a new _window_ instead of tab.

This is kept as a hidden option since it doesn’t work 100 %. I’ll revisit again as more users of this feature show up.

### CODE REVIEW

**Comment by lydell** [comment]
@ceasal Would you mind testing builds from this pull request? That’s a much faster feedback cycle than publishing “for real” which can take weeks.

1. Install one of the builds below. (It sounds like you use Firefox but I added Chrome as well just in case.)
2. Go to Link Hints Options.
3. Scroll to the bottom of the page.
4. Expand the “Debug” section.
5. Scroll to the “PREFER_WINDOWS” option.
6. Enable it!

### Firefox

1. Download this zip: [link_hints-1.2.3.zip](https://github.com/lydell/LinkHints/files/8747961/link_hints-1.2.3.zip)
2. Go to `about:debugging`.
3. Click “This Firefox” in the sidebar.
4. Click the “Load Temporary Add-on…” button.
5. Choose the zip file you downloaded.
6. Now you should be able to test the version from this PR until you restart Firefox!

### Chrome

1. Download this zip: [link_hints-1.2.3.zip](https://github.com/lydell/LinkHints/files/8747958/link_hints-1.2.3.zip)  (Note: Another zip than for Firefox.)
2. Unzip it into a folder.
7. Go to `chrome://extensions` in Chrome.
8. Disable your current Link Hints installation.
9. Enable the “Developer mode” switch in the top right corner.
10. Click “Load unpacked” in the top left corner.
11. Choose the folder you unpacked the zip into.
12. Now you should be able to try it out!

**Comment by ceasal** [comment]
Tested in Firefox 99.0.1

After checking `prefer windows` in debug,

`Alt+K`, `Alt+L` both open new windows.
 `Alt+Shift+K` opens a new window but stays in hinting mode when switching back to the window, although the new window is focused immediately.
`Alt+J` and holding `Alt` when activating the last key in a hint opens in a new tab as well.

The binds seem to also perform as they did before when the debug flag is not checked.

**Comment by ceasal** [comment]
I added some machinery to my window manager to ignore focus changes for Chrome and Firefox windows.

On Chromium 100.0.4896.127, the `K` bindings open in the background and `L` opens in the foreground, corroborating your testing.

Firefox does the opposite: a newly spawned window is not focused, while any window opened from a middle click will be focused.

From my simple testing on X11, when a page is loaded in a new window, it seems Firefox sends a `_NET_ACTIVE_WINDOW` signal after opening a new window from a link in another. Chrome does not send such a request.

I tried opening a new window from a terminal, e.g. `firefox --new-tab http://google.com` but the signal it still sent.

**Comment by lydell** [comment]
Thanks for the testing!

On macOS, Chrome works perfectly with background/foreground windows. It works just like with tabs. While Firefox seems to _always_ focus new windows. So on Firefox, `Alt+K` and `Alt+L` are effectively the same, and `Alt+Shift+K` just feels broken when you use it.

Is this still good enough for you? If so, I think I might merge this as-is and keep it as a hidden “debug” option. Partly because few Link Hints users seem to need it, partly because it doesn’t work 100 %.

**Comment by ceasal** [comment]
Yes, it's reasonable to keep the option hidden given the behavior isn't consistent.

**Pull request merged**
